name: Deploy Vue App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: dev
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |

            set -e

            APP_DIR="/srv/docker/apps/selin-web"
            REPO="git@github.com:EmirGuven/selin-web.git"
            APP_DATA_DIR="$APP_DIR/data-db"
            APP_UPLOADS_DIR="$APP_DIR/uploads"

            echo "📁 Preparing application directory..."
            mkdir -p $APP_DIR
            mkdir -p $APP_DATA_DIR
            mkdir -p $APP_UPLOADS_DIR
            cd $APP_DIR

            echo "📦 Checking repository..."

            if [ ! -d ".git" ]; then
              echo "⬇️ Cloning repository..."
              git init
              git remote add origin $REPO
              git fetch origin main
              git reset --hard origin/main
            else
              echo "🔄 Pulling latest changes..."
              git reset --hard
              git pull origin main
            fi

            echo "🐳 Building and starting containers..."
            docker compose up -d --build

            echo "🧹 Cleaning unused docker images..."
            docker image prune -f

            echo "✅ Deploy completed successfully"
